# Generated by Django 5.2.1 on 2025-12-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sessionresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id']},
        ),
    ]
